import sqlite3 from 'sqlite3';

sqlite3.verbose();

const home = [
  {
    matchDate: '2024-08-21',
    event: 'Champions League (Europa)',
    home: 'Young Boys',
    away: 'Galatasaray',
    homeScore: '3',
    awayScore: '2',
  },
  {
    matchDate: '2024-08-16',
    event: 'Super Lig (Turcia)',
    home: 'Konyaspor',
    away: 'Galatasaray',
    homeScore: '1',
    awayScore: '2',
  },
  {
    matchDate: '2024-08-09',
    event: 'Super Lig (Turcia)',
    home: 'Galatasaray',
    away: 'Hatayspor',
    homeScore: '2',
    awayScore: '1',
  },
  {
    matchDate: '2024-08-03',
    event: 'Super Cupa (Turcia)',
    home: 'Galatasaray',
    away: 'Besiktas',
    homeScore: '0',
    awayScore: '5',
  },
  {
    matchDate: '2024-07-27',
    event: 'Meciuri amicale între cluburi (Lume)',
    home: 'Galatasaray',
    away: 'Parma',
    homeScore: '0',
    awayScore: '2',
  },
  {
    matchDate: '2024-07-24',
    event: 'Meciuri amicale între cluburi (Lume)',
    home: 'Galatasaray',
    away: 'Lecce',
    homeScore: '2',
    awayScore: '1',
  },
  {
    matchDate: '2024-07-18',
    event: 'Meciuri amicale între cluburi (Lume)',
    home: 'Galatasaray',
    away: 'Trencin',
    homeScore: '4',
    awayScore: '1',
  },
  {
    matchDate: '2024-07-15',
    event: 'Meciuri amicale între cluburi (Lume)',
    home: 'Dusseldorf',
    away: 'Galatasaray',
    homeScore: '5',
    awayScore: '2',
  },
  {
    matchDate: '2024-07-11',
    event: 'Meciuri amicale între cluburi (Lume)',
    home: 'LASK',
    away: 'Galatasaray',
    homeScore: '3',
    awayScore: '2',
  },
  {
    matchDate: '2024-05-26',
    event: 'Super Lig (Turcia)',
    home: 'Konyaspor',
    away: 'Galatasaray',
    homeScore: '1',
    awayScore: '3',
  },
  {
    matchDate: '2024-05-19',
    event: 'Super Lig (Turcia)',
    home: 'Galatasaray',
    away: 'Fenerbahce',
    homeScore: '0',
    awayScore: '1',
  },
  {
    matchDate: '2024-05-12',
    event: 'Super Lig (Turcia)',
    home: 'Karagumruk',
    away: 'Galatasaray',
    homeScore: '2',
    awayScore: '3',
  },
  {
    matchDate: '2024-05-05',
    event: 'Super Lig (Turcia)',
    home: 'Galatasaray',
    away: 'Sivasspor',
    homeScore: '6',
    awayScore: '1',
  },
  {
    matchDate: '2024-04-26',
    event: 'Super Lig (Turcia)',
    home: 'Adana Demirspor',
    away: 'Galatasaray',
    homeScore: '0',
    awayScore: '3',
  },
  {
    matchDate: '2024-04-21',
    event: 'Super Lig (Turcia)',
    home: 'Galatasaray',
    away: 'Pendikspor',
    homeScore: '4',
    awayScore: '1',
  },
  {
    matchDate: '2024-04-15',
    event: 'Super Lig (Turcia)',
    home: 'Alanyaspor',
    away: 'Galatasaray',
    homeScore: '0',
    awayScore: '4',
  },
  {
    matchDate: '2024-04-07',
    event: 'Super Cupa (Turcia)',
    home: 'Galatasaray',
    away: 'Fenerbahce',
    homeScore: '3',
    awayScore: '0',
  },
  {
    matchDate: '2024-04-02',
    event: 'Super Lig (Turcia)',
    home: 'Galatasaray',
    away: 'Hatayspor',
    homeScore: '1',
    awayScore: '0',
  },
  {
    matchDate: '2024-03-17',
    event: 'Super Lig (Turcia)',
    home: 'Kasimpasa',
    away: 'Galatasaray',
    homeScore: '3',
    awayScore: '4',
  },
  {
    matchDate: '2024-03-08',
    event: 'Super Lig (Turcia)',
    home: 'Galatasaray',
    away: 'Rizespor',
    homeScore: '6',
    awayScore: '2',
  },
  {
    matchDate: '2024-03-03',
    event: 'Super Lig (Turcia)',
    home: 'Besiktas',
    away: 'Galatasaray',
    homeScore: '0',
    awayScore: '1',
  },
  {
    matchDate: '2024-02-29',
    event: 'Cupa (Turcia)',
    home: 'Galatasaray',
    away: 'Karagumruk',
    homeScore: '0',
    awayScore: '2',
  },
  {
    matchDate: '2024-02-26',
    event: 'Super Lig (Turcia)',
    home: 'Galatasaray',
    away: 'Antalyaspor',
    homeScore: '2',
    awayScore: '1',
  },
  {
    matchDate: '2024-02-22',
    event: 'Europa League (Europa)',
    home: 'Sparta Praga',
    away: 'Galatasaray',
    homeScore: '4',
    awayScore: '1',
  },
  {
    matchDate: '2024-02-18',
    event: 'Super Lig (Turcia)',
    home: 'Ankaragucu',
    away: 'Galatasaray',
    homeScore: '0',
    awayScore: '3',
  },
  {
    matchDate: '2024-02-15',
    event: 'Europa League (Europa)',
    home: 'Galatasaray',
    away: 'Sparta Praga',
    homeScore: '3',
    awayScore: '2',
  },
  {
    matchDate: '2024-02-10',
    event: 'Super Lig (Turcia)',
    home: 'Galatasaray',
    away: 'Basaksehir',
    homeScore: '2',
    awayScore: '0',
  },
  {
    matchDate: '2024-02-06',
    event: 'Cupa (Turcia)',
    home: 'Galatasaray',
    away: 'Bandirmaspor',
    homeScore: '4',
    awayScore: '2',
  },
  {
    matchDate: '2024-02-02',
    event: 'Super Lig (Turcia)',
    home: 'Samsunspor',
    away: 'Galatasaray',
    homeScore: '0',
    awayScore: '2',
  },
  {
    matchDate: '2024-01-29',
    event: 'Super Lig (Turcia)',
    home: 'Galatasaray',
    away: 'Gaziantep',
    homeScore: '2',
    awayScore: '1',
  },
  {
    matchDate: '2024-01-25',
    event: 'Super Lig (Turcia)',
    home: 'Galatasaray',
    away: 'Istanbulspor',
    homeScore: '3',
    awayScore: '1',
  },
  {
    matchDate: '2024-01-21',
    event: 'Super Lig (Turcia)',
    home: 'Trabzonspor',
    away: 'Galatasaray',
    homeScore: '1',
    awayScore: '5',
  },
  {
    matchDate: '2024-01-18',
    event: 'Cupa (Turcia)',
    home: 'Galatasaray',
    away: 'Umraniyespor',
    homeScore: '4',
    awayScore: '1',
  },
  {
    matchDate: '2024-01-15',
    event: 'Super Lig (Turcia)',
    home: 'Galatasaray',
    away: 'Kayserispor',
    homeScore: '2',
    awayScore: '1',
  },
  {
    matchDate: '2024-01-11',
    event: 'Super Lig (Turcia)',
    home: 'Sivasspor',
    away: 'Galatasaray',
    homeScore: '1',
    awayScore: '1',
  },
  {
    matchDate: '2024-01-07',
    event: 'Super Lig (Turcia)',
    home: 'Galatasaray',
    away: 'Konyaspor',
    homeScore: '3',
    awayScore: '0',
  },
  {
    matchDate: '2023-12-24',
    event: 'Super Lig (Turcia)',
    home: 'Fenerbahce',
    away: 'Galatasaray',
    homeScore: '0',
    awayScore: '0',
  },
  {
    matchDate: '2023-12-20',
    event: 'Super Lig (Turcia)',
    home: 'Galatasaray',
    away: 'Karagumruk',
    homeScore: '1',
    awayScore: '0',
  },
  {
    matchDate: '2023-12-12',
    event: 'Champions League (Europa)',
    home: 'FC Copenhaga',
    away: 'Galatasaray',
    homeScore: '1',
    awayScore: '0',
  },
  {
    matchDate: '2023-12-08',
    event: 'Super Lig (Turcia)',
    home: 'Galatasaray',
    away: 'Adana Demirspor',
    homeScore: '3',
    awayScore: '1',
  },
  {
    matchDate: '2023-12-02',
    event: 'Super Lig (Turcia)',
    home: 'Pendikspor',
    away: 'Galatasaray',
    homeScore: '0',
    awayScore: '2',
  },
  {
    matchDate: '2023-11-29',
    event: 'Champions League (Europa)',
    home: 'Galatasaray',
    away: 'Manchester Utd',
    homeScore: '3',
    awayScore: '3',
  },
  {
    matchDate: '2023-11-25',
    event: 'Super Lig (Turcia)',
    home: 'Galatasaray',
    away: 'Alanyaspor',
    homeScore: '4',
    awayScore: '0',
  },
  {
    matchDate: '2023-11-11',
    event: 'Super Lig (Turcia)',
    home: 'Hatayspor',
    away: 'Galatasaray',
    homeScore: '2',
    awayScore: '1',
  },
  {
    matchDate: '2023-11-08',
    event: 'Champions League (Europa)',
    home: 'Bayern',
    away: 'Galatasaray',
    homeScore: '2',
    awayScore: '1',
  },
  {
    matchDate: '2023-11-03',
    event: 'Super Lig (Turcia)',
    home: 'Galatasaray',
    away: 'Kasimpasa',
    homeScore: '2',
    awayScore: '1',
  },
  {
    matchDate: '2023-10-28',
    event: 'Super Lig (Turcia)',
    home: 'Rizespor',
    away: 'Galatasaray',
    homeScore: '0',
    awayScore: '1',
  },
  {
    matchDate: '2023-10-24',
    event: 'Champions League (Europa)',
    home: 'Galatasaray',
    away: 'Bayern',
    homeScore: '1',
    awayScore: '3',
  },
  {
    matchDate: '2023-10-21',
    event: 'Super Lig (Turcia)',
    home: 'Galatasaray',
    away: 'Besiktas',
    homeScore: '2',
    awayScore: '1',
  },
  {
    matchDate: '2023-10-07',
    event: 'Super Lig (Turcia)',
    home: 'Antalyaspor',
    away: 'Galatasaray',
    homeScore: '0',
    awayScore: '2',
  },
];
const away = [
  {
    matchDate: '2024-08-21',
    event: 'Champions League (Europa)',
    home: 'Young Boys',
    away: 'Galatasaray',
    homeScore: '3',
    awayScore: '2',
  },
  {
    matchDate: '2024-08-17',
    event: 'Cupa Elveţiei (Elveţia)',
    home: 'Printse-Nendaz',
    away: 'Young Boys',
    homeScore: '0',
    awayScore: '10',
  },
  {
    matchDate: '2024-08-10',
    event: 'Super League (Elveţia)',
    home: 'Yverdon',
    away: 'Young Boys',
    homeScore: '2',
    awayScore: '2',
  },
  {
    matchDate: '2024-08-04',
    event: 'Super League (Elveţia)',
    home: 'Young Boys',
    away: 'Zurich',
    homeScore: '2',
    awayScore: '2',
  },
  {
    matchDate: '2024-07-28',
    event: 'Super League (Elveţia)',
    home: 'St. Gallen',
    away: 'Young Boys',
    homeScore: '4',
    awayScore: '0',
  },
  {
    matchDate: '2024-07-24',
    event: 'Super League (Elveţia)',
    home: 'Servette',
    away: 'Young Boys',
    homeScore: '3',
    awayScore: '1',
  },
  {
    matchDate: '2024-07-21',
    event: 'Super League (Elveţia)',
    home: 'Young Boys',
    away: 'Sion',
    homeScore: '1',
    awayScore: '2',
  },
  {
    matchDate: '2024-07-13',
    event: 'Meciuri amicale între cluburi (Lume)',
    home: 'Young Boys',
    away: 'Wil',
    homeScore: '1',
    awayScore: '3',
  },
  {
    matchDate: '2024-07-13',
    event: 'Meciuri amicale între cluburi (Lume)',
    home: 'Young Boys',
    away: 'Aarau',
    homeScore: '1',
    awayScore: '0',
  },
  {
    matchDate: '2024-07-10',
    event: 'Meciuri amicale între cluburi (Lume)',
    home: 'Kryvbas',
    away: 'Young Boys',
    homeScore: '2',
    awayScore: '2',
  },
  {
    matchDate: '2024-07-06',
    event: 'Meciuri amicale între cluburi (Lume)',
    home: 'Westerlo',
    away: 'Young Boys',
    homeScore: '1',
    awayScore: '0',
  },
  {
    matchDate: '2024-07-02',
    event: 'Meciuri amicale între cluburi (Lume)',
    home: 'Young Boys',
    away: 'Xamax',
    homeScore: '4',
    awayScore: '0',
  },
  {
    matchDate: '2024-06-28',
    event: 'Meciuri amicale între cluburi (Lume)',
    home: 'Breitenrain',
    away: 'Young Boys',
    homeScore: '1',
    awayScore: '2',
  },
  {
    matchDate: '2024-06-28',
    event: 'Meciuri amicale între cluburi (Lume)',
    home: 'Young Boys',
    away: 'Thun',
    homeScore: '0',
    awayScore: '2',
  },
  {
    matchDate: '2024-05-25',
    event: 'Super League (Elveţia)',
    home: 'Young Boys',
    away: 'Winterthur',
    homeScore: '3',
    awayScore: '0',
  },
  {
    matchDate: '2024-05-20',
    event: 'Super League (Elveţia)',
    home: 'Servette',
    away: 'Young Boys',
    homeScore: '0',
    awayScore: '1',
  },
  {
    matchDate: '2024-05-16',
    event: 'Super League (Elveţia)',
    home: 'Young Boys',
    away: 'St. Gallen',
    homeScore: '3',
    awayScore: '1',
  },
  {
    matchDate: '2024-05-11',
    event: 'Super League (Elveţia)',
    home: 'Young Boys',
    away: 'Lugano',
    homeScore: '0',
    awayScore: '1',
  },
  {
    matchDate: '2024-05-05',
    event: 'Super League (Elveţia)',
    home: 'Zurich',
    away: 'Young Boys',
    homeScore: '0',
    awayScore: '2',
  },
  {
    matchDate: '2024-04-21',
    event: 'Super League (Elveţia)',
    home: 'Winterthur',
    away: 'Young Boys',
    homeScore: '1',
    awayScore: '2',
  },
  {
    matchDate: '2024-04-14',
    event: 'Super League (Elveţia)',
    home: 'Young Boys',
    away: 'Luzern',
    homeScore: '4',
    awayScore: '2',
  },
  {
    matchDate: '2024-04-07',
    event: 'Super League (Elveţia)',
    home: 'St. Gallen',
    away: 'Young Boys',
    homeScore: '2',
    awayScore: '2',
  },
  {
    matchDate: '2024-04-04',
    event: 'Super League (Elveţia)',
    home: 'Young Boys',
    away: 'Grasshoppers',
    homeScore: '3',
    awayScore: '0',
  },
  {
    matchDate: '2024-04-01',
    event: 'Super League (Elveţia)',
    home: 'Yverdon',
    away: 'Young Boys',
    homeScore: '0',
    awayScore: '0',
  },
  {
    matchDate: '2024-03-17',
    event: 'Super League (Elveţia)',
    home: 'Lausanne',
    away: 'Young Boys',
    homeScore: '2',
    awayScore: '0',
  },
  {
    matchDate: '2024-03-10',
    event: 'Super League (Elveţia)',
    home: 'Young Boys',
    away: 'FC Basel',
    homeScore: '5',
    awayScore: '1',
  },
  {
    matchDate: '2024-03-03',
    event: 'Super League (Elveţia)',
    home: 'Zurich',
    away: 'Young Boys',
    homeScore: '1',
    awayScore: '0',
  },
  {
    matchDate: '2024-02-29',
    event: 'Cupa Elveţiei (Elveţia)',
    home: 'Sion',
    away: 'Young Boys',
    homeScore: '2',
    awayScore: '1',
  },
  {
    matchDate: '2024-02-25',
    event: 'Super League (Elveţia)',
    home: 'Young Boys',
    away: 'Servette',
    homeScore: '0',
    awayScore: '1',
  },
  {
    matchDate: '2024-02-22',
    event: 'Europa League (Europa)',
    home: 'Sporting',
    away: 'Young Boys',
    homeScore: '1',
    awayScore: '1',
  },
  {
    matchDate: '2024-02-18',
    event: 'Super League (Elveţia)',
    home: 'Young Boys',
    away: 'Lausanne Ouchy',
    homeScore: '1',
    awayScore: '0',
  },
  {
    matchDate: '2024-02-15',
    event: 'Europa League (Europa)',
    home: 'Young Boys',
    away: 'Sporting',
    homeScore: '1',
    awayScore: '3',
  },
  {
    matchDate: '2024-02-10',
    event: 'Super League (Elveţia)',
    home: 'Lugano',
    away: 'Young Boys',
    homeScore: '3',
    awayScore: '3',
  },
  {
    matchDate: '2024-02-03',
    event: 'Super League (Elveţia)',
    home: 'Lausanne',
    away: 'Young Boys',
    homeScore: '0',
    awayScore: '1',
  },
  {
    matchDate: '2024-01-30',
    event: 'Super League (Elveţia)',
    home: 'Young Boys',
    away: 'Yverdon',
    homeScore: '5',
    awayScore: '1',
  },
  {
    matchDate: '2024-01-27',
    event: 'Super League (Elveţia)',
    home: 'FC Basel',
    away: 'Young Boys',
    homeScore: '1',
    awayScore: '0',
  },
  {
    matchDate: '2024-01-20',
    event: 'Super League (Elveţia)',
    home: 'Young Boys',
    away: 'Grasshoppers',
    homeScore: '1',
    awayScore: '0',
  },
  {
    matchDate: '2024-01-13',
    event: 'Meciuri amicale între cluburi (Lume)',
    home: 'Young Boys',
    away: 'Wil',
    homeScore: '1',
    awayScore: '0',
  },
  {
    matchDate: '2024-01-13',
    event: 'Meciuri amicale între cluburi (Lume)',
    home: 'Young Boys',
    away: 'Vaduz',
    homeScore: '3',
    awayScore: '2',
  },
  {
    matchDate: '2024-01-09',
    event: 'Meciuri amicale între cluburi (Lume)',
    home: 'Young Boys',
    away: 'Sion',
    homeScore: '4',
    awayScore: '3',
  },
  {
    matchDate: '2023-12-16',
    event: 'Super League (Elveţia)',
    home: 'Lausanne Ouchy',
    away: 'Young Boys',
    homeScore: '1',
    awayScore: '3',
  },
  {
    matchDate: '2023-12-13',
    event: 'Champions League (Europa)',
    home: 'RB Leipzig',
    away: 'Young Boys',
    homeScore: '2',
    awayScore: '1',
  },
  {
    matchDate: '2023-12-09',
    event: 'Super League (Elveţia)',
    home: 'Young Boys',
    away: 'St. Gallen',
    homeScore: '3',
    awayScore: '0',
  },
  {
    matchDate: '2023-12-06',
    event: 'Super League (Elveţia)',
    home: 'Young Boys',
    away: 'Lausanne Ouchy',
    homeScore: '1',
    awayScore: '0',
  },
  {
    matchDate: '2023-12-03',
    event: 'Super League (Elveţia)',
    home: 'Young Boys',
    away: 'Servette',
    homeScore: '1',
    awayScore: '1',
  },
  {
    matchDate: '2023-11-28',
    event: 'Champions League (Europa)',
    home: 'Young Boys',
    away: 'Steaua Roșie B.',
    homeScore: '2',
    awayScore: '0',
  },
  {
    matchDate: '2023-11-25',
    event: 'Super League (Elveţia)',
    home: 'Zurich',
    away: 'Young Boys',
    homeScore: '3',
    awayScore: '1',
  },
  {
    matchDate: '2023-11-11',
    event: 'Super League (Elveţia)',
    home: 'Young Boys',
    away: 'Luzern',
    homeScore: '6',
    awayScore: '1',
  },
  {
    matchDate: '2023-11-07',
    event: 'Champions League (Europa)',
    home: 'Manchester City',
    away: 'Young Boys',
    homeScore: '3',
    awayScore: '0',
  },
  {
    matchDate: '2023-11-04',
    event: 'Super League (Elveţia)',
    home: 'Winterthur',
    away: 'Young Boys',
    homeScore: '1',
    awayScore: '4',
  },
];
const h2h = [
  {
    matchDate: '2024-08-21',
    event: 'Champions League (Europa)',
    home: 'Young Boys',
    away: 'Galatasaray',
    homeScore: '3',
    awayScore: '2',
  },
  {
    matchDate: '2016-07-19',
    event: 'Uhren Cup (Europa)',
    home: 'Young Boys',
    away: 'Galatasaray',
    homeScore: '1',
    awayScore: '1',
  },
];

let db = new sqlite3.Database('matchDb.db', (err) => {
  if (err) {
    console.error(err.message);
  }
  console.log('Connected to database');
  db.serialize(() => {
    db.serialize(() => {
      //create home table
      db.run(
        'CREATE TABLE homeTeam (matchDate INTEGER, event TEXT, home TEXT, away TEXT, homeScore INTEGER, awayScore INTEGER)'
      );
      //insert into home table
      let stmt = db.prepare(
        `INSERT INTO homeTeam (matchDate, event, home, away, homeScore, awayScore) VALUES ((SELECT unixepoch($matchDate)), $event, $home, $away, $homeScore, $awayScore)`
      );
      home.forEach((el) => {
        stmt.run({
          $matchDate: el.matchDate,
          $event: el.event,
          $home: el.home,
          $away: el.away,
          $homeScore: parseInt(el.homeScore, 10),
          $awayScore: parseInt(el.awayScore, 10),
        });
      });
      stmt.finalize();
    });
    db.serialize(() => {
      //create away table
      db.run(
        'CREATE TABLE awayTeam (matchDate INTEGER, event TEXT, home TEXT, away TEXT, homeScore INTEGER, awayScore INTEGER)'
      );
      //insert into away table
      let stmt = db.prepare(
        `INSERT INTO awayTeam (matchDate, event, home, away, homeScore, awayScore) VALUES ((SELECT unixepoch($matchDate)), $event, $home, $away, $homeScore, $awayScore)`
      );
      away.forEach((el) => {
        stmt.run({
          $matchDate: el.matchDate,
          $event: el.event,
          $home: el.home,
          $away: el.away,
          $homeScore: parseInt(el.homeScore, 10),
          $awayScore: parseInt(el.awayScore, 10),
        });
      });
      stmt.finalize();
    });
    db.serialize(() => {
      //create h2h table
      db.run(
        'CREATE TABLE h2h (matchDate INTEGER, event TEXT, home TEXT, away TEXT, homeScore INTEGER, awayScore INTEGER)'
      );
      //insert into h2h table
      let stmt = db.prepare(
        `INSERT INTO h2h (matchDate, event, home, away, homeScore, awayScore) VALUES ((SELECT unixepoch($matchDate)), $event, $home, $away, $homeScore, $awayScore)`
      );
      h2h.forEach((el) => {
        stmt.run({
          $matchDate: el.matchDate,
          $event: el.event,
          $home: el.home,
          $away: el.away,
          $homeScore: parseInt(el.homeScore, 10),
          $awayScore: parseInt(el.awayScore, 10),
        });
      });
      stmt.finalize();
    });
  });
  db.close((err) => {
    if (err) {
      console.error(err.message);
    }
    console.log('Close the database connection.');
  });
});
